apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-oom
  annotations:
    description: "The container will fail with OOM"
  labels:
    app: node-oom
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: node-oom 
  template:
    metadata:
      labels:
        app: node-oom
    spec:
      containers:
      - name: node-oom
        image: noamasela/node-oom:1.0
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "15Mi"
          limits:
            memory: "20Mi"
            cpu: 1
