apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-oom
  annotations:
    description: "The container will fail with OOM"
  labels:
    app: node-oom
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: node-oom 
  template:
    metadata:
      labels:
        app: node-oom
    spec:
      containers:
      - name: node-oom
        image: noamasela/node-oom:1.8
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "15Mi"
            cpu: 100m
          limits:
            memory: "225Mi"
            cpu: 1
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=22"
        - name: DUMP_PATH
          value: "/dumps"
        volumeMounts:
        - name: heap-dumps
          mountPath: /dumps
      - name: ship-heap-dump
#        image: uadevnet/alpine-inotify-tools:latest
        image: ubuntu
        command: ["/bin/bash", "-c"]
        args:
        - |
          #!/bin/bash
          apt update &&
          apt install inotify-tools -y &&
          inotifywait -m /dumps -e close_write | while read dump_file; do echo "file $dump_file" ; done
        volumeMounts:
        - name: heap-dumps
          mountPath: /dumps
        resources:
          requests:
            memory: "15Mi"
            cpu: 100m
          limits:
            memory: "1024Mi"
            cpu: 2
      volumes:
      - name: heap-dumps
        persistentVolumeClaim:
          claimName: node-oom-pvc
